apiVersion: v1
kind: PersistentVolume
metadata:
  name: ngx-config-nfs-pv
  #Name of PV where it stores the configuration directory/files
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ngx-config
  #PVC below uses this name to associate PV
  nfs:
    server: 192.168.1.10
    #The configuration files are stored  in NFS
    path: "/mnt/md1/ngx-config"
    #This is the NFS mount point
  mountOptions:
    - hard
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ngx-config-pvc
  #Name of PVC
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ngx-config 
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngxslb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngxslb
  template:
    metadata:
      labels:
        app: ngxslb
    spec:
      containers:
      - name: ngxslb
        image: nginx
        volumeMounts:
        - name: config-volv
          mountPath: "/etc/nginx"
        ports:
        - containerPort: 9090
      volumes:
      - name: config-volv
        persistentVolumeClaim:
          claimName: ngx-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ngxslb-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: ngxslb
  ports:
    - name: listen9090 
      port: 9090
      targetPort: 9090
      nodePort: 32222






